### ISSUE TITLE
Provider - MeliMedia

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/Claws#100]
URL: https://bit.ly/2UqlypI
Content Type: Universal
DDL: Yes
Accept-Ranges (DDL Only): bytes
Real-Debrid: No
CloudFlare Protection: No

Example film page: https://bit.ly/2IEXbCo
Example show page: https://bit.ly/2GlEWPF
Example video URL: https://bit.ly/2v7YJNd

**Comment by kevincosmos** [comment]
In Progress with Teek.

**Comment by Teekzilla** [comment]
Closing as this is completed in #94.

**Comment by kevincosmos** [comment]
@Teekzilla are we not planning on implementing the TV shows as discussed?

**Comment by kevincosmos** [comment]
Reopening as the provider is picking up dubbed audio links with no video:

See https://bit.ly/2UoY6cv
Link called "Separate audio dubbed Persian" which links to video file https://bit.ly/2XnUols - I have downloaded and verified that this is only an audio file (even though it's a .mkv) and have also confirmed that the link is passed through Claws.

**Comment by Teekzilla** [comment]
Updated #101. That's the best were are going to get to filtering those audio tracks out currently.

**Comment by Teekzilla** [comment]
@kevincosmos That was for MoviesWeb. At least that's what I was referring to. We're you talking about TV shows for this site?

**Comment by kevincosmos** [comment]
@Teekzilla you're right :)

**Comment by Teekzilla** [comment]
Closing as it has been confirmed as being fixed by #101.

**Comment by kevincosmos** [comment]
Reopening (again) as Teek has found an issue with this provider giving dubbed results, see dialog:
They have separate pages for normal and dubbed I think
If you search Spider-Man: Into the Spider-Verse
Search returns Spider-Man...Dubbed and Spider-Man
And because the title matches the dubbed first
It goes that route
can't do anything about Spider-Man because it doesn't contain the 'Dubbed' string in the search
Unless we want to search every hit that matches instead
But still gotta check for dubbed on search because other movies have that
Might just search every hit though
Might double the work in rare edge cases
But will guarentee we don't get dubbed
Using both double and guarantee loosely
