### ISSUE TITLE
VPN and Proxy

### ISSUE THREAD

**Issue by Freyaman** [ApolloTVofficial/Claws#154]
https://kb.adguard.com/en/android/solving-problems/tasker#available-actions

Will fix the issue your having

**Comment by Freyaman** [comment]
https://kb.adguard.com/en/android/solving-problems/tasker#available-actions

You need a place to put in PIN Code on you app

**Comment by NBTX** [comment]
What issue? Also this is the Claws repository, the app is Kamino...
