### ISSUE TITLE
How to generate the clientId manually ?

### ISSUE THREAD

**Issue by tarek369** [ApolloTVofficial/Claws#155]
I wanna generate the clientId manually to try it and add new providers and enhance it.

**Comment by corkiejp** [comment]
Make sure your using the release version and not the master, as there is incomplete broken code in the master.

https://github.com/ApolloTVofficial/Claws/releases

or alternatively this version of it.
https://github.com/ddivad/Klaws

As for the server key, you can use your own random string of numbers+letters, don't have to have a generated version. If that is what your mean by clientid

**Comment by tarek369** [comment]
Thanks for this advice
Now i have added SECRET_CLIENT_ID in env file 
now i want to auth from postman, so i need to generate client ID but i dont know how ?

**Comment by tarek369** [comment]
Also when i try GET 127.0.0.1:3000/api/v1/search/movies 
i always get 404 !

**Comment by corkiejp** [comment]
Try your machine ip address instead of localhost?

**Comment by tarek369** [comment]
not working still,
127.0.0.1:3000/api/v1/status works

**Comment by corkiejp** [comment]
Doesn't work on public server as well.
https://server.apollotv.xyz/api/v1/search/movies
As i said the **master code is broken**, and them commands might not have been finalized are implement in release candidate.

**Comment by NBTX** [comment]
If I recall correctly, the master code isn't broken if you're using it independently of the client-side app. @corkiejp 
It's only broken when you're using it with the app.

**Comment by NBTX** [comment]
@tarek369 You're not meant to send a `GET` request to that endpoint, all of the API documentation is shamefully outdated 😬from months ago. We don't use server sent events anymore.

You're actually meant to open a socket. You can see an example implementation in JavaScript here: https://github.com/ApolloTVofficial/Claws/blob/master/public/ui/index.html

**Comment by tarek369** [comment]
wooow Thanks a lot 👍  I will try to discover the code
