### ISSUE TITLE
How to resolve event scrape ?

### ISSUE THREAD

**Issue by tarek369** [ApolloTVofficial/Claws#157]
I have msg like {cookieRequired: ""
event: "scrape"
provider: "GoWatchSeries"
resolver: "Openload"
scrapeId: "1a0e19be-37f3-48a9-a0f0-27a807ec8b5b"
target: "https://openload.co/embed/R4hjwrIcB_U?c1_file=https://sub.movie-series.net/limitless-hd-720p/limitless-hd-720p.vtt&c1_label=English"}

how to get the final link ?

**Comment by NBTX** [comment]
This is for if you're building an app, it proxies the request client-side to bypass IP locking.

If you're just working with the server, you can set `CLAWS_ENV="client"` in your `.env` file.

**Comment by tarek369** [comment]
Thanks ! it did the magic 

if you can provide me tutorial or documentation how to add new providers, that will be helpful

**Comment by NBTX** [comment]
That is something we're working on.

**Comment by tarek369** [comment]
perfect 👌
