### ISSUE TITLE
Scraper Name = "null" in Search Results

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/Claws#16]
As shown in the below image, some scraper names appear as "Null"

I'd suggest that if we can't get the scraper name for any given reason, we give it a generic name like "Apollo" or "Houston"

![screenshot_20190212-081930](https://user-images.githubusercontent.com/30179692/52622560-01b92000-2ea2-11e9-9bee-dd5eaade9006.png)

**Comment by NBTX** [comment]
I disagree with providing a generic name. That's misleading and unhelpful. We should make it something like 'Unknown' or ideally a user-friendly synonym for 'Undefined' in that case.

This is mainly an issue with the server not providing the name though, so I will transfer this issue to Claws and keep an eye on it.

**Comment by kevincosmos** [comment]
Closing as fixed by PR53.
