### ISSUE TITLE
Bypass CloudFlare AntiDOS

### ISSUE THREAD

**Issue by FlyPigsFly** [ApolloTVofficial/Claws#31]
See here: https://github.com/codemanki/cloudscraper

The benefits of this would be access to more providers and higher quality links.

Example provider to make use of would be:
ddlvalley.me

**Comment by SpajicM** [comment]
Hey!

This looks like it may be a good idea, but I've a few concerns:
- Looking at example usage: `cloudscraper.get('http://website.com/',` it looks like we'd have to replace all calls with cloudscraper, which means providers using cloudscraper would probably differentiate quite a bit from current providers, using cheerio. Our aim is to try and streamline providers and make them structurally as similar as possible. Maybe something could be done with BaseProvider?
- I'm not sure if it's a good idea to use a one-man-library for core functionality of our scraping server.
I see repository is actively being commited to, but there are also a few still opened PRs all the way back to 2016/2017, which I don't think is a good sign in terms of project maintanance and stability. Some of those unclosed PRs include adding and/or improving promises, which would probably affect us too.

**Comment by FlyPigsFly** [comment]
There's also https://github.com/Kamikadze4GAME/cloudflare-bypasser

**Comment by txzkroos** [comment]
@FlyPigsFly @SpajicM the cloudflare-bypasser looks good 
you should pull that code into Claws and maintain it yourselves

In `BaseProvider` get rid of `request-promise` and use a popular well tested library like `axios` for networking

The cloudflare handling will then be added as a default axios middleware/intercepter ready to handle all cloudflare pages.

https://github.com/freund17/axios-cloudflare
You should include https://github.com/Kamikadze4GAME/cloudflare-bypasser/pull/5 too

Simple 😎

**Comment by SpajicM** [comment]
Wait so what are you suggesting?

Kamikadze4GAME's cloudflare-bypasser or Axios + axios-cloudflare?
The latter sounds good except it wasn't updated for 2 years...

**Comment by txzkroos** [comment]
I'm suggesting

- Switch to axios
- Create our own cloudflare intercepter using code from those two libraries as guides.

cloudflare-bypasser should be the main code to copy over then use the axios-cloudflare as guide for how to do the interceptor

That makes more sense to me 😎

**Comment by SpajicM** [comment]
Aha, gotcha. 
Yes, that would allow us integrate CF bypass without much code diversion from the other providers.

I'll leave it up to @ddivad  or @claws-dev for further comments.

**Comment by pro-src** [comment]
cloudscraper v3.0.0 is about to be published. It has full promise support and is a drop in replacement for request-promise. The cloudflare-bypasser is essentially a fork of cloudscraper and is that developer's first public package. The developer of cloudflare-bypasser is/was a contributor of cloudscraper. They sent one single PR that was merged iirc and then went on to republish??? It is insecure and doesn't have the features and/or popularity of cloudscraper. Not to mention they've neglected to update their package even after somebody sent a security related PR.... Just saying... Wait for us to publish the v3.0.0 branch and use cloudscraper as it has been and will continue to be maintained for the foreseeable future.

Disclaimer: I spent the past few weeks helping to prepare the v3.0.0 release.

**Comment by pro-src** [comment]
Also, note that cloudscraper has great unit tests that run on CI with 100% code coverage. It's all on the v3.0.0 branch which is soon to be published.

**Comment by pro-src** [comment]
@codemanki

**Comment by SpajicM** [comment]
@pro-src Thank you for the update! Appreciated!

I'm wondering could/should we then move all calls to cloudscraper and it's gonna work fine if site doesn't use CF, or we would still need to take care which scrapers/sites have CF and treat them differently according to that?

**Comment by pro-src** [comment]
@SpajicM, you can use it for all sites whether they use cloudflare or not. cloudscraper should be almost indistinguishable from request-promise. The reason I say almost is because there's a couple of default request options to be aware of, specifically `followAllRedirects` and `headers` but you can pass any option that request or request-promise supports. You can also change any default option except `followAllRedirects` without problems. Although, I would leave the `Accept` header alone as not to hint to Cloudflare that your requests aren't originating from a web browser. Obviously, it uses a browser's user agent string but you can set your own. The README.md will be updated soon.

**Comment by pro-src** [comment]
@SpajicM, to be direct, yes, you should absolutely do that and things will work fine.

**Comment by FlyPigsFly** [comment]
@SpajicM if we moved all scrapers to use this bypass it would be great for future proofing. More code updating upfront but then in the future if a provider started using cloudflare we wouldn't have worry since we already accounted for that. 

Maybe for now though test this out on a few providers that use cloudflare like ddlvalley.me

**Comment by pro-src** [comment]
[cloudscraper v3.0.0](https://www.npmjs.com/package/cloudscraper) was just publish. There isn't any support for piping right not and there are some open issues. Good luck guys!

**Comment by SpajicM** [comment]
Fixed by https://github.com/ApolloTVofficial/Claws/pull/127
