### ISSUE TITLE
Avoid same duplicate links in providers due to URL aliases

### ISSUE THREAD

**Issue by txzkroos** [ApolloTVofficial/Claws#35]
E.g. [Afdah](https://github.com/ApolloTVofficial/Claws/blob/99eb4e8/src/scrapers/providers/movies/Afdah.js#L187) always resolves duplicate links because each URL is an alias of each other.

Is it safe to assume this URLs looping logic is there to combat ISP blockages?

We should add some kind of (optional?) logic on booting up Claws which goes through the providers and then "pings" their URLs and return unique non-alias URLs that can be accessed. Meaning if the URLs shares the same scrape logic but returns different results, then that'll be fine to keep.

It's a waste of time and resources making the same requests 5 times.

**Comment by SpajicM** [comment]
Based on what you would detect that URL is a duplicate? We've had some discussion on duplicates, but I'm not sure if this is covered?

**Comment by kevincosmos** [comment]
I think the plans that are planned to be implemented would cover this.

I believe the plans are that if the app detects the same file name (astarisborn.h265.whatever.mp4) on the same resolver (openload) given by the same provider (solarmovie.sc) then the link will be filtered out.

As an example of this - solarmovie has 300+ links for "Boy Erased" which are all hosted on openload and have the exact same file name, so we would filter out those duplicates.

**Comment by txzkroos** [comment]
@SpajicM I'm thinking along the lines of maybe

```
// These should maybe be functions or different class properties, you decide.
urlDefinitions = {
   aliases: ['aliasProxy1', 'aliasProxy2', 'aliasProxy3' ], // alternative URL aliases/proxies to bypass ISPs.
   alternatives: [ 'altUrl1', 'altUrl2' ] // alternative sites sharing the same process but returning different results.
}
```

I'm thinking maybe

1. Implement a `bootstrapUrls` function in the base provider.
2. On starting up claws, loop through all the providers and call `bootstrapUrls`
3. `bootstrapUrls` processes the `aliases` on boot picking the first or fastest one the current Claws instance can ping, and combine it with `alternatives` and use them for the `scrape` for loop. The `getUrls` function will then return the optimised URL list.

@kevincosmos it's hacky but that could work as well, I just find it annoying and wasteful to see code making the exact same network requests multiple times for no real reason at all when it could be avoided.

**Comment by kevincosmos** [comment]
Closing issue as requested by @SpajicM as this has already been covered by work implemented by @claws-dev

**Comment by txzkroos** [comment]
Where is @Claws-dev's work on this? I would like to know his approach
