### ISSUE TITLE
MasterAnime Closing - remove provider

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/Claws#44]
See screenshot:

https://media.discordapp.net/attachments/489504213496234014/553009646986854421/image1.png?width=663&height=498

**Comment by SpajicM** [comment]
Removed in #45

**Comment by kevincosmos** [comment]
will close after #45 is reviewed and merged

**Comment by kevincosmos** [comment]
#45 merged, issue closed.
