### ISSUE TITLE
resolveHtml refactor

### ISSUE THREAD

**Issue by SpajicM** [ApolloTVofficial/Claws#61]
resolveHtml was left out in recent mass rename fix by ClawsDev, but seems due to rewrite anyhow:

- shows resolver name as "provider"
- some pass dataObject, some pass dataObject.file, dataObject.link, dataObject.src. This should be standardized.
- doesn't pick up provider name at all (server.js, data.provider)
- It's a massive if-else
- Passes empty quality parameter (prepare for future filename regex?)
- Resolver names are hardcoded twice instead of passing on 'resolver' parameter
- Something I'm confused about:

Some resolvers are done like:

```
    if (resolver === 'Openload') {
        return [createEvent(data, false, {}, {quality: '', provider: 'Openload', cookie, isResultOfScrape: true})];
```
but some other ones have a forEach?
```
    } else if (resolver === 'Vidoza') {
        const dataList = [];
        data.forEach(dataObject => {
            dataList.push(createEvent(dataObject.src, false, {}, {quality: dataObject.res, provider: 'Vidoza', cookie, isResultOfScrape: true}));
        });
        return dataList;
```

**Comment by claws-dev** [comment]
All html resolvers need to return an array of events. In Openload's case, it only resolves 1 link per source URL. In Vidoza's case, it can resolve multiple links per source URL.

**Comment by kevincosmos** [comment]
> All html resolvers need to return an array of events. In Openload's case, it only resolves 1 link per source URL. In Vidoza's case, it can resolve multiple links per source URL.

This is also the case with RapidVideo, could this be the reason why RapidVideo links don't appear in the Chrome console?

Here is a valid RapidVideo URL resolved by Claws: https://www.rapidvideo.com/e/G1ECRSCWF1 

It actually has 3 links related to it
https://www.rapidvideo.com/e/G1ECRSCWF1&q=720p
https://www.rapidvideo.com/e/G1ECRSCWF1&q=480p
https://www.rapidvideo.com/e/G1ECRSCWF1&q=360p

This is what is seen in Chrome Console
![image](https://user-images.githubusercontent.com/30179692/54986525-bae33d80-4faa-11e9-8b1f-ca6f2e052d30.png)

**Comment by SpajicM** [comment]
Fixed by https://github.com/ApolloTVofficial/Claws/pull/74
